In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('homeprices.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())


In [4]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
x = df[['area', 'bedrooms', 'age']]
y = df['price']

In [6]:
model = LinearRegression().fit(x,y)
model

LinearRegression()

In [7]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
model.intercept_

221323.00186540408

In [9]:
model.predict([[9000,9,7]])

C:\Users\haier\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1417762.87468564])

In [10]:
112.06244194 * 9000 + 23388.88007794 * 9 + -3231.71790863 * 7 + 221323.00186540408

1417762.8746664538

In [11]:
dff = pd.read_csv('F:\SMIT DS\Task 02-01-2025\hiring.csv')

In [12]:
dff

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
dff['test_score(out of 10)'] = dff['test_score(out of 10)'].fillna(dff['test_score(out of 10)'].median())

In [14]:
dff

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
experience_mapping = {
    "zero": 0,
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
}
dff.experience = dff.experience.map(experience_mapping)

In [16]:
dff

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [17]:
dff.experience = dff.experience.fillna(dff.experience.median())

In [18]:
dff

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [19]:
xx = dff[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
yy = dff['salary($)']

In [20]:
model = LinearRegression().fit(xx,yy)
model

LinearRegression()

In [21]:
model.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [22]:
model.intercept_

11869.91869918695

In [23]:
model.predict([[15,15,15]])

C:\Users\haier\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([117967.4796748])

In [24]:
2813.00813008 * 15 + 1333.33333333 * 15 + 2926.82926829 * 15 + 11869.91869918695

117967.47967468695