In [ ]:
pip install Numpy

In [3]:
import numpy as np
l = [1,2,3,4,5,6]
arry = np.array(l) # output in int value
arry1 = np.array(l,dtype=float) # output in float value
arry2 = np.array(l,dtype='U32') # output in string value
print(arry)
print(arry1)
print(arry2)
print(type(arry))

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>


In [14]:
l3 = [[1,1,1],[2,2,2],[3,3,3]]
array3 = np.array(l3) # output in 3d array
print(array3)
print(array3.ndim)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
2


In [6]:
array4 = np.arange(1,8)
print(array4)

[1 2 3 4 5 6 7]


In [17]:
array5 = np.arange(1,7).reshape(2,3) # output 2 row and 3 coloum
print(array5)

[[1 2 3]
 [4 5 6]]


In [8]:
array6 = np.arange(1,10).reshape(3,3) # output 3 row and 3 coloum
print(array6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
array7 = np.zeros((4,2))
print(array7)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
array8 = np.ones((4,2))
print(array8)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
array8 = np.ones(4)
print(array8)

[1. 1. 1. 1.]


Atributes of Numpy Array
1. ndim
2. shape
3. size
4. dtype
5. itemsize

In [12]:
list1 = [1,2,3,4,5]
aray1 = np.array(list1)
print(aray1.ndim)
print(aray1.shape)

1
(5,)


In [20]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
aray2 = np.array(list2)
print(aray2.ndim)
print(aray2.shape)

2
(3, 3)


In [9]:
# list3 = [[[1,2,3],[4,5,6]],[[7,8,9],[3,4,5]]] # output (2,2,3)
# list3 = [[[1,2,3],[4,5,6],[4,5,6]],[[7,8,9],[3,4,5],[4,5,6]]] # output (2,3,3)
list3 = [[[1,2,3],[4,5,6],[4,5,6]],[[7,8,9],[3,4,5],[4,5,6]],[[7,8,9],[3,4,5],[4,5,6]]] # output (3,3,3)
aray3 = np.array(list3)
# print(aray3)
print(aray3.ndim)
print(aray3.shape)

3
(3, 3, 3)


In [10]:
a = np.array('482')
b = np.array([10, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1.0, 2.0, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6.0]], [[1, 2, 3], [4, 5, 6]]])
print('Array of a :', a)
print('Array of b :', b)
print('Array of c :', c)
print('Array of d :', d)
print('Dimensions of a : ',a.ndim)
print('Dimensions of b : ',b.ndim)
print('Dimensions of c : ',c.ndim)
print('Dimensions of d : ',d.ndim)

print('Shape of a :',a.shape)
print('Shape of b :',b.shape)
print('Shape of c :',c.shape)
print('Shape of d :',d.shape)

print('Size of a :', a.size)
print('Size of b :', b.size)
print('Size of c :', c.size)
print('Size of d :', d.size)

print('Type of a :', a.dtype)
print('Type of b :', b.dtype)
print('Type of c :', c.dtype)
print('Type of d :', d.dtype)

print('Item size of a :', a.itemsize)
print('Item size of b :', b.itemsize)
print('Item size of c :', c.itemsize)
print('Item size of d :', d.itemsize)

Array of a : 482
Array of b : [10  2  3  4  5]
Array of c : [[1 2 3]
 [4 5 6]]
Array of d : [[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]]
Dimensions of a :  0
Dimensions of b :  1
Dimensions of c :  2
Dimensions of d :  3
Shape of a : ()
Shape of b : (5,)
Shape of c : (2, 3)
Shape of d : (3, 2, 3)
Size of a : 1
Size of b : 5
Size of c : 6
Size of d : 18
Type of a : <U3
Type of b : int32
Type of c : int32
Type of d : float64
Item size of a : 12
Item size of b : 4
Item size of c : 4
Item size of d : 8


In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
import numpy as np
ll = [22,33,44,55,66]
arr = np.array(ll)
print(arr)
print(arr.ndim)
print(arr.shape)

[22 33 44 55 66]
1
(5,)


In [13]:
# Indexing of array
aa = np.array('482')
bb = np.array([10, 2, 3, 4, 5])
cc = np.array([[1, 2, 3], [4, 5, 6]])
dd = np.array([[[1.0, 2.0, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6.0]], [[1, 2, 3], [4, 5, 6]]])
# print(aa[])
print(bb[3])
print(cc[0,1])
print('Row of 2 :',dd[2,:])
print('Coloum of 1 :',dd[:, 1])

4
2
Row of 2 : [[1. 2. 3.]
 [4. 5. 6.]]
Coloum of 1 : [[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


In [14]:
import numpy as np
l = [22,33,44,55,66]
arr = np.array(l)
print(arr)

[22 33 44 55 66]


In [17]:
print('dtype of arr :' , arr.dtype)
print('size of arr :' , arr.size)
print('ndim of arr :' , arr.ndim)
print('itemsize of arr :', arr.itemsize)

dtype of arr : int32
size of arr : 5
ndim of arr : 1
itemsize of arr : 4


In [18]:
import numpy as np 
x = np.array([4,6,7,4,3,1,9,7,66])
print(x)

[ 4  6  7  4  3  1  9  7 66]


In [19]:
# it will return sorted copy of an array
y = np.sort(np.array([3,4,6,8,9,7,6,5,4,4,3,2,2,1]))
print(y)

[1 2 2 3 3 4 4 4 5 6 6 7 8 9]


In [20]:
# it will return the indices that would sort an array
y = np.argsort(np.array([3,4,6,8,9,7,6,5,4,4,3,2,2,1]))
print(y)

[13 11 12  0 10  1  8  9  7  2  6  5  3  4]


In [21]:
# use array name and sort it in_place
z = np.array([3,4,6,8,9,7,6,5,4,4,3,2,2,1])
print(z)
z.sort()
print(z)

[3 4 6 8 9 7 6 5 4 4 3 2 2 1]
[1 2 2 3 3 4 4 4 5 6 6 7 8 9]


In [22]:
print(z)

[1 2 2 3 3 4 4 4 5 6 6 7 8 9]


# Statistical operations on 1D array 
1. max()
2. min()
3. sum()
4. mean()
5. median()
6. prod()
7. var()
8. std()

In [17]:
import numpy as np # 1D
x = np.array([4,6,7,8,3,4,1])
y = f"Max num of the array: {np.max(x):>5}"
y1 = f"Min num of the array: {np.min(x):>5}"
y2 = f"Sum of the array: {np.sum(x):>5}"
y3 = f"Mean of the array: {np.mean(x):.2f}" # mean = total sum of all element / total no of element
y4 = f"Median of the array: {np.median(x):>5}" # first element sorted and fined median element
y5 = f"Product of the array: {np.prod(x):>5}" # product of all element
y6 = f"Variance of the array: {np.var(x):>5.2f}"# Variance is a measure of how much the numbers in the array differ from their mean.
y7 = f"Standard Deviation of the array: {np.std(x):>5.2f}" # square root of variance
print(y)
print(y1)
print(y2)
print(y3)
print(y4)
print(y5)
print(y6)
print(y7)

Max num of the array:     8
Min num of the array:     1
Sum of the array:    33
Mean of the array: 4.71
Median of the array:   4.0
Product of the array: 16128
Variance of the array:  5.06
Standard Deviation of the array:  2.25


In [1]:
import numpy as np # 2D
x = np.array([[4,6,7,8,3,4,1],[44,66,77,88,33,44,11]])
y = f"Max num of the array: {np.max(x):>5}"
y1 = f"Min num of the array: {np.min(x):>5}"
y2 = f"Sum of the array: {np.sum(x):>5}"
y3 = f"Mean of the array: {np.mean(x):.2f}" # mean = total sum of all element / total no of element
y4 = f"Median of the array: {np.median(x):>5}" # first element sorted and fined median element
y5 = f"Product of the array: {np.prod(x):>5}" # product of all element
y6 = f"Variance of the array: {np.var(x):>5.2f}"# Variance is a measure of how much the numbers in the array differ from their mean.
y7 = f"Standard Deviation of the array: {np.std(x):>5.2f}" # square root of variance
print(y)
print(y1)
print(y2)
print(y3)
print(y4)
print(y5)
print(y6)
print(y7)

Max num of the array:    88
Min num of the array:     1
Sum of the array:   396
Mean of the array: 28.29
Median of the array:   9.5
Product of the array: -1472004096
Variance of the array: 864.35
Standard Deviation of the array: 29.40


In [1]:
import numpy as np # 3D
x = np.array([[[4,6,7,8,3,4,1],[44,66,77,88,33,44,11],[444,666,777,888,333,444,111]]])
y = f"Max num of the array: {np.max(x):>5}"
y1 = f"Min num of the array: {np.min(x):>5}"
y2 = f"Sum of the array: {np.sum(x):>5}"
y3 = f"Mean of the array: {np.mean(x):.2f}" # mean = total sum of all element / total no of element
y4 = f"Median of the array: {np.median(x):>5}" # first elements sorted then fined median element
y5 = f"Product of the array: {np.prod(x):>5}" # product of all element
y6 = f"Variance of the array: {np.var(x):>5.2f}"# Variance is a measure of how much the numbers in the array differ from their mean.
y7 = f"Standard Deviation of the array: {np.std(x):>5.2f}" # square root of variance
print(y)
print(y1)
print(y2)
print(y3)
print(y4)
print(y5)
print(y6)
print(y7)

Max num of the array:   888
Min num of the array:     1
Sum of the array:  4059
Mean of the array: 193.29
Median of the array:  44.0
Product of the array: 1392508928
Variance of the array: 75812.68
Standard Deviation of the array: 275.34


In [13]:
j = [3,5,6,3,2,2,1]
j = np.array(j, ndmin = 6)
print(j)
print(j.dtype)
print(j.ndim)
print(j.shape)
print(j.itemsize)
print(j.base)
print(j.ctypes)
print(j.data)
print(j.flags)

[[[[[[3 5 6 3 2 2 1]]]]]]
int32
6
(1, 1, 1, 1, 1, 7)
4
[3 5 6 3 2 2 1]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [3]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [5]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [6]:
class Bank_Account: 
    def __init__(self,name, balance ): 
        self.name = name
        self.balance = balance
    def deposit(self, deposit_amount):
        self.deposit_amount = deposit_amount
        self.balance += deposit_amount
        print(f"{self.name} Your Deposit Amount {self.deposit_amount} and Current Balance {self.balance}.")
    def withdraw(self,withdraw_amount): 
        self.withdraw_amount = withdraw_amount
        if withdraw_amount < self.balance:
            self.balance -= withdraw_amount
        else:
            print("Insuffiction Balance!")
        print(f"{self.name} Your Withdraw Amount {self.withdraw_amount} and Current Balance {self.balance}.")
hamza = Bank_Account("Hamza", 1000)
hamza.deposit(100)
hamza.withdraw(200)
saleem = Bank_Account("Saleem" , 2000)
saleem.deposit(100)
saleem.withdraw(200)

Hamza Your Deposit Amount 100 and Current Balance 1100.
Hamza Your Withdraw Amount 200 and Current Balance 900.
Saleem Your Deposit Amount 100 and Current Balance 2100.
Saleem Your Withdraw Amount 200 and Current Balance 1900.
